apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h8pu662uf-python 
  janus-idp.io/tekton: h8pu662uf-python
  backstage.io/kubernetes-id: h8pu662uf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h8pu662uf-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml